### PR TITLE
fix: remove SATA license

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
because it is conflict with CC BY-SA 4.0
CC BY-SA don't allow additional restriction (https://creativecommons.org/licenses/by-sa/4.0/)
Need all contributors agree.

- [x] @saeziae 
- [x] @CoelacanthusHex 
- [x] @llh721113 
- [x] @KevinZonda 
- [ ] @kenchiu233 
- [x] @Misaka13514 
- [x] @IndigoMad 
- [ ] @Chiaki2333 
- [ ] @KaguraTart 
- [x] @undefined-moe 
- [x] @Cattttttttt 
- [ ] @Subarupan 
- [ ] @ezrameow 
- [ ] @wychlw 
- [x] @Xeonacid

### CODE REVIEW

**Review by undefined-moe — APPROVED** [review]

**Comment by saeziae** [comment]
Not sure if it is forbidden by CC. In my idea it is literally forbidden sharers from adding other rules.
However, it is better to remove it, as our website visitors are not all GitHub users. It is strange for a website to ask their visitors to star the coding proyect when share.

**Review by saeziae — APPROVED** [review]

**Comment by undefined-moe** [comment]
> Not sure if it is forbidden by CC. In my idea it is literally forbidden sharers from adding other rules.

个人观点：`ShareAlike` 限制为对此行为的限制（不得附加条款），而 `No additional restrictions` 指发布时不允许附加额外条款。

**Review by KevinZonda — APPROVED** [review]
I think we have to remove SATA if we use CC SA 4.0. Or we can modify CC license.

**Comment by re-xyr** [comment]
> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

This looks very weird. After all one can compose a license equivalent to CC-BY-SA *without* this rule. I cannot see why we can't do so. I think this is a restriction on modification and/or redistribution instead of the original work.

**Comment by KevinZonda** [comment]
> > Not sure if it is forbidden by CC. In my idea it is literally forbidden sharers from adding other rules.
> 
> 个人观点：`ShareAlike` 限制为对此行为的限制（不得附加条款），而 `No additional restrictions` 指发布时不允许附加额外条款。

But actually, the rule also mentions that
> You may not apply legal terms or technological measures that legally **restrict others from doing anything the license permits**.

I'm doubting that will SATA do anything restricts users?

**Comment by Misaka13514** [comment]
I prefer to remove SATA license. Just do it with the results of your discussion.

**Review by Misaka13514 — APPROVED** [review]

**Review by IndigoMad — APPROVED** [review]

**Review by Xeonacid — APPROVED** [review]
I have no objection to removing SATA.
But I think the new version of SATA (thanks to https://github.com/zTrix/sata-license/pull/6) has no conflict with CC-BY-SA.

> By [RFC 2119](https://tools.ietf.org/html/rfc2119):
> 
> > MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
> > definition is an absolute requirement of the specification.
> 
> > SHOULD   This word, or the adjective "RECOMMENDED", mean that there
> > may exist valid reasons in particular circumstances to ignore a
> > particular item, but the full implications must be understood and
> > carefully weighed before choosing a different course.

**Comment by Cattttttttt** [comment]
草我是不是按错了什么

**Pull request merged**
